name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI, Kubectl, and Helm
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip
          
          # Update AWS CLI if already installed
          if aws --version &>/dev/null; then
            echo "AWS CLI already installed, updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          
          aws --version

      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Logging in to AWS ECR..."
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }} && break || sleep 10
          done


      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t backend:${{ env.COMMIT_ID }} .
          docker tag backend:${{ env.COMMIT_ID }} ${{ secrets.ECR_REPO }}:${{ env.COMMIT_ID }}

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to ECR..."
          docker push ${{ secrets.ECR_REPO }}:${{ env.COMMIT_ID }}

  deploy:
    name: Deploy Backend to EKS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI, Kubectl, and Helm
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip
          
          # Install AWS CLI
          if command -v aws &>/dev/null; then
            echo "AWS CLI already installed, updating..."
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          aws --version
          
          # Install Kubectl
          curl -sLO "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          kubectl version --client
          
          # Install Helm
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Get Commit ID
        run: echo "COMMIT_ID=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          
      - name: Configure AWS CLI for EKS
        run: |
          echo "Configuring AWS CLI for EKS..."
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Deploy Backend with Helm
        run: |
          echo "Deploying Backend with Helm..."
          helm upgrade --install ${{ secrets.HELM_RELEASE }} ./${{ secrets.HELM_REPO_PATH }} \
            -f ${{ secrets.HELM_REPO_PATH }}/values.yaml \
            --set image.backend.tag=${{ env.COMMIT_ID }} \
            --description "Git Commit ${{ env.COMMIT_ID }}"
          
          cat ./${{ secrets.HELM_REPO_PATH }}/values.yaml

      - name: Restart Backend Deployment
        run: |
          echo "Restarting Backend Deployment..."
          kubectl rollout restart deployment ${{ secrets.BACKEND_DEPLOYMENT_NAME }}
